package com.test;

public class ExceptionTest {
	public static void main(String[] args) {
		
		//we can't use try() because try is reserved keyword 
		/*try(){
			
		}
		finally{
			
		}*/
		
		
		
		
		//normal scenario  we can use with catch or without catch but with finally 
		/*try{
			int i=0;
		}catch(Exception e){
			
		}
		finally{
			
		}*/
	}
}
